# Generated by Django 5.2.9 on 2026-01-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coin_balance',
            field=models.IntegerField(default=0, help_text='Coin balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, help_text='Current level'),
        ),
        migrations.AddField(
            model_name='user',
            name='shield_count',
            field=models.IntegerField(default=1, help_text='Streak shields (1 free at start)'),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=0, help_text='Experience points'),
        ),
    ]
