# Generated by Django 5.2.9 on 2026-02-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_coin_balance_user_level_user_shield_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict, help_text='{"daily_reminder": true, "streak_warning": true, "achievements": true, "marketing": false}'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='{"dark_mode": false, "sound_effects": true, "language": "vi", "cards_per_day": 20}'),
        ),
    ]
