# Generated by Django 5.2.9 on 2026-01-08 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='anki_file',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='classroom',
        ),
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('FINISHED', 'Đã kết thúc'), ('DRAFT', 'Bản nháp')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='deck',
            name='appwrite_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deck',
            name='appwrite_file_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='deck',
            name='card_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField(default=45, help_text='Thời gian làm bài (phút)')),
                ('question_count', models.IntegerField(default=20)),
                ('shuffle', models.BooleanField(default=True)),
                ('show_result', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('ACTIVE', 'Đang diễn ra'), ('COMPLETED', 'Hoàn thành')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lms.classroom')),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='lms.deck')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
