# Generated by Django 5.2.9 on 2026-01-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_deck_anki_file_remove_deck_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='join_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
