# Generated by Django 5.2.9 on 2026-01-09 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_deck_anki_file_remove_deck_classroom_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='deck',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Đang xử lý'), ('DRAFT', 'Bản nháp'), ('ACTIVE', 'Đang hoạt động')], default='PROCESSING', max_length=20),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(help_text='Mặt trước (câu hỏi)')),
                ('back', models.TextField(help_text='Mặt sau (trả lời)')),
                ('note_id', models.CharField(blank=True, help_text='ID gốc từ Anki', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lms.deck')),
            ],
        ),
    ]
