# Generated by Django 5.2.9 on 2026-01-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_classroom_decks_classroom_join_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='join_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
