# Generated by Django 5.2.9 on 2026-01-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_classroom_join_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='lms_assignment',
        ),
        migrations.AlterModelTable(
            name='testsubmission',
            table='lms_assignmentsubmission',
        ),
    ]
