# Generated by Django 5.2.9 on 2026-01-09 06:00
# Fake migration to match Heroku state - no actual operations needed

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_classroom_join_code'),
    ]

    operations = [
        # These AlterModelTable operations match the db_table settings in models.py
        # Already applied on Heroku via --fake
        migrations.AlterModelTable(
            name='test',
            table='lms_assignment',
        ),
        migrations.AlterModelTable(
            name='testsubmission',
            table='lms_assignmentsubmission',
        ),
    ]
