# Generated by Django 5.2.9 on 2026-01-11 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_test_table_alter_testsubmission_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='version',
            field=models.IntegerField(default=1, help_text='Auto-incremented on update'),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration_seconds', models.IntegerField(default=0)),
                ('cards_reviewed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='lms.deck')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(help_text='Anki card ID', max_length=50)),
                ('ease', models.IntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')])),
                ('time_taken', models.IntegerField(help_text='Milliseconds')),
                ('reviewed_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lms.studysession')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Mở'), ('IN_PROGRESS', 'Đang xử lý'), ('CLOSED', 'Đã đóng')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao')], default='MEDIUM', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['student', 'deck'], name='lms_studyse_student_0b8f74_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['created_at'], name='lms_studyse_created_b10867_idx'),
        ),
        migrations.AddIndex(
            model_name='cardreview',
            index=models.Index(fields=['card_id', 'reviewed_at'], name='lms_cardrev_card_id_88a131_idx'),
        ),
        migrations.AddIndex(
            model_name='cardreview',
            index=models.Index(fields=['session'], name='lms_cardrev_session_443225_idx'),
        ),
    ]
