# Generated by Django 5.2.9 on 2026-01-17 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_anki_addon_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, help_text='Current consecutive days studied')),
                ('longest_streak', models.IntegerField(default=0, help_text='Longest streak ever achieved')),
                ('last_study_date', models.DateField(blank=True, help_text='Last date the student reviewed cards', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anki_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnkiRevlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revlog_id', models.BigIntegerField(help_text='Anki revlog.id (timestamp in milliseconds)')),
                ('card_id', models.BigIntegerField(help_text='Anki card ID')),
                ('usn', models.IntegerField(help_text='Update sequence number (-1 for local changes)')),
                ('button_chosen', models.SmallIntegerField(help_text='1=Again, 2=Hard, 3=Good, 4=Easy, 0=Manual')),
                ('interval', models.IntegerField(help_text='New interval (positive=days, negative=seconds)')),
                ('last_interval', models.IntegerField(help_text='Previous interval')),
                ('ease_factor', models.IntegerField(help_text='Ease factor * 1000 (e.g., 2500 = 250%)')),
                ('taken_millis', models.IntegerField(help_text='Time spent answering in milliseconds')),
                ('review_kind', models.SmallIntegerField(help_text='0=Learn, 1=Review, 2=Relearn, 3=Filtered, 4=Manual')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anki_revlogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', '-revlog_id'], name='lms_ankirev_student_f735c3_idx'), models.Index(fields=['card_id'], name='lms_ankirev_card_id_46981d_idx'), models.Index(fields=['student', 'button_chosen'], name='lms_ankirev_student_97b78a_idx')],
                'unique_together': {('student', 'revlog_id')},
            },
        ),
        migrations.CreateModel(
            name='DailyStudyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cards_reviewed', models.IntegerField(default=0, help_text='Total cards reviewed')),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Total time spent studying')),
                ('cards_learned', models.IntegerField(default=0, help_text='New cards learned (review_kind=0)')),
                ('cards_relearned', models.IntegerField(default=0, help_text='Cards relearned after lapse (review_kind=2)')),
                ('retention_rate', models.FloatField(default=0.0, help_text="Percentage of cards not marked 'Again' (0.0 to 1.0)")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_study_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily study stats',
                'indexes': [models.Index(fields=['student', '-date'], name='lms_dailyst_student_c52ce1_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
