# Generated by Django 5.2.9 on 2026-01-26 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_cointransaction_classroomjoinrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('CARDS', 'Số thẻ học'), ('TIME', 'Thời gian học (phút)'), ('STREAK', 'Streak liên tục (ngày)'), ('XP', 'Điểm XP')], max_length=20)),
                ('target_value', models.IntegerField(help_text='Mục tiêu cần đạt')),
                ('reward_xp', models.IntegerField(default=0)),
                ('reward_coins', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, help_text='Null = Global event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lms.classroom')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, help_text='Current progress towards target')),
                ('baseline', models.IntegerField(default=0, help_text='Starting value when joined')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rewarded', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lms.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-progress'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', '-start_date'], name='lms_event_is_acti_7083aa_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['classroom', 'is_active'], name='lms_event_classro_3541d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'user')},
        ),
    ]
