# Generated by Django 5.2.9 on 2026-01-26 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_event_eventparticipant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('achievement_type', models.CharField(choices=[('STREAK', 'Streak liên tục'), ('CARDS', 'Số thẻ học'), ('XP', 'Điểm XP'), ('TIME', 'Thời gian học'), ('LEVEL', 'Level đạt được'), ('SPECIAL', 'Đặc biệt')], max_length=20)),
                ('target_value', models.IntegerField(default=1)),
                ('rarity', models.CharField(choices=[('COMMON', 'Thường'), ('RARE', 'Hiếm'), ('EPIC', 'Sử thi'), ('LEGENDARY', 'Huyền thoại')], default='COMMON', max_length=20)),
                ('reward_xp', models.IntegerField(default=0)),
                ('reward_coins', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'achievement_type', 'target_value'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('rewarded', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unlocks', to='lms.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
