# Generated by Django 5.2.9 on 2026-01-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='fields',
            field=models.JSONField(blank=True, default=dict, help_text='All note fields as JSON'),
        ),
        migrations.AddField(
            model_name='card',
            name='note_type',
            field=models.CharField(blank=True, help_text='Note type/template name', max_length=255),
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Card tags'),
        ),
    ]
