# Generated by Django 5.2.9 on 2026-01-26 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_card_fields_card_note_type_card_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20)),
                ('price', models.IntegerField(default=0, help_text='Giá coin (0 = miễn phí)')),
                ('downloads', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_items', to=settings.AUTH_USER_MODEL)),
                ('deck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_item', to='lms.deck')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='lms_marketp_status_b2b234_idx')],
            },
        ),
    ]
