# Generated by Django 5.2.9 on 2026-02-01 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_marketplaceitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CARD_REVIEW', 'Reviewed cards'), ('CLASS_JOIN', 'Joined class'), ('CLASS_CREATE', 'Created class'), ('DECK_CREATE', 'Created deck'), ('DECK_UPLOAD', 'Uploaded deck'), ('TEST_SUBMIT', 'Submitted test'), ('ACHIEVEMENT', 'Unlocked achievement'), ('LOGIN', 'Logged in')], max_length=50)),
                ('description', models.TextField()),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
