# Generated by Django 5.2.9 on 2026-02-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_type',
            field=models.CharField(choices=[('CLASS', 'Lớp học'), ('GROUP', 'Nhóm học tập')], default='CLASS', max_length=10),
        ),
        migrations.AddField(
            model_name='classroom',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Công khai cho mọi người tìm kiếm'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='max_students',
            field=models.PositiveIntegerField(default=50, help_text='Số lượng học viên tối đa'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='topics',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách chủ đề (tags)'),
        ),
    ]
