# Generated by Django 5.2.9 on 2026-02-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_advanced_class_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deck',
            name='origin',
            field=models.CharField(choices=[('UPLOAD', 'Uploaded'), ('WEB', 'Created Online')], default='UPLOAD', max_length=10),
        ),
    ]
